# name:            the English name for the language.
# translated_name: the 'local' name for the language.
# in_prod:         If true, include in the language switcher.
# html_only:       If true, only create HTML files.
# sphinxopts:      Extra options to pass to SPHINXOPTS in the Makefile.

# Remember to update the Salt config with redirects for new translations!
# For example: https://github.com/python/psf-salt/commit/14bdc3ae054468092e5a8c3cdacfd02f43c32e19

[defaults]
# name has no default, it is mandatory.
translated_name = ""
in_prod = true
html_only = false
sphinxopts = [
    "-D latex_engine=xelatex",
    "-D latex_elements.inputenc=",
    "-D latex_elements.fontenc=",
]

[languages.el]
name = "Greek"
translated_name = "Ελληνικά"

[languages.en]
name = "English"

[languages.es]
name = "Spanish"
translated_name = "español"
sphinxopts = [
    '-D latex_engine=xelatex',
    '-D latex_elements.inputenc=',
    '-D latex_elements.fontenc=\\usepackage{fontspec}',
]

[languages.fr]
name = "French"
translated_name = "français"
sphinxopts = [
    '-D latex_engine=xelatex',
    '-D latex_elements.inputenc=',
    '-D latex_elements.fontenc=\\usepackage{fontspec}',
]

[languages.bn_IN]
name = "Bengali"
translated_name = "বাংলা"
in_prod = false

[languages.id]
name = "Indonesian"
translated_name = "Indonesia"
in_prod = false

[languages.it]
name = "Italian"
translated_name = "italiano"

[languages.ja]
name = "Japanese"
translated_name = "日本語"
sphinxopts = [
    '-D latex_engine=lualatex',
    '-D latex_elements.inputenc=',
    '-D latex_elements.fontenc=',
    '-D latex_docclass.manual=ltjsbook',
    '-D latex_docclass.howto=ltjsarticle',

    # supress polyglossia warnings
    '-D latex_elements.polyglossia=',
    '-D latex_elements.fontpkg=',

    # preamble
    # Render non-Japanese letters with luatex
    # https://gist.github.com/zr-tex8r/e0931df922f38fbb67634f05dfdaf66b
    # Workaround for the luatex-ja issue (Thanks to @jfbu)
    # https://github.com/sphinx-doc/sphinx/issues/11179#issuecomment-1420715092
    # https://osdn.net/projects/luatex-ja/ticket/47321
    # subpress warning: (fancyhdr)Make it at least 16.4pt
    '-D latex_elements.preamble=\\usepackage[noto-otf]{luatexja-preset}\\usepackage{newunicodechar}\\newunicodechar{^^^^212a}{K}\\makeatletter\\titleformat{\\subsubsection}{\\normalsize\\py@HeaderFamily}{\\py@TitleColor\\thesubsubsection}{0.5em}{\\py@TitleColor}\\titleformat{\\paragraph}{\\normalsize\\py@HeaderFamily}{\\py@TitleColor\\theparagraph}{0.5em}{\\py@TitleColor}\\titleformat{\\subparagraph}{\\normalsize\\py@HeaderFamily}{\\py@TitleColor\\thesubparagraph}{0.5em}{\\py@TitleColor}\\makeatother\\setlength{\\footskip}{16.4pt}'
]

[languages.ko]
name = "Korean"
translated_name = "한국어"
sphinxopts = [
    '-D latex_engine=xelatex',
    '-D latex_elements.inputenc=',
    '-D latex_elements.fontenc=',
    '-D latex_elements.preamble=\\usepackage{kotex}\\setmainhangulfont{UnBatang}\\setsanshangulfont{UnDotum}\\setmonohangulfont{UnTaza}',
]

[languages.pl]
name = "Polish"
translated_name = "polski"

[languages.pt_BR]
name = "Brazilian Portuguese"
translated_name = "Português brasileiro"

[languages.ro]
name = "Romanian"
translated_name = "Românește"

[languages.ru]
name = "Russian"
translated_name = "Русский"

[languages.sv]
name = "Swedish"
translated_name = "Svenska"
in_prod = false

[languages.tr]
name = "Turkish"
translated_name = "Türkçe"

[languages.uk]
name = "Ukrainian"
translated_name = "українська"
in_prod = false
html_only = true

[languages.zh_CN]
name = "Simplified Chinese"
translated_name = "简体中文"
sphinxopts = [
    '-D latex_engine=xelatex',
    '-D latex_elements.inputenc=',
    '-D latex_elements.fontenc=\\usepackage{xeCJK}',
]

[languages.zh_TW]
name = "Traditional Chinese"
translated_name = "繁體中文"
sphinxopts = [
    '-D latex_engine=xelatex',
    '-D latex_elements.inputenc=',
    '-D latex_elements.fontenc=\\usepackage{xeCJK}',
]
